import React from "react";
import {
  FilePlus2,
  UploadCloud,
  CalendarDays,
  GraduationCap,
  Ticket,
  AlertTriangle,
  FileSignature,
  Award,
  BookOpenCheck,
  History,
  BookMarked,
  UserCheck,
  TrendingUp,
  CalendarClock,
  ClipboardCheck,
} from "lucide-react";

export const ExamLinks = () => {
  return [
    // {
    //   title: "Course Assignment",
    //   description:
    //     "Assign courses to semesters and manage the course roster.",
    //   path: "/exam/course-assignment",
    //   icon: <BookOpenCheck size={22} strokeWidth={2.5} />,
    //   color: "text-sky-600",
    //   bg: "bg-sky-100",
    //   accent: "bg-sky-600",
    // },
    // {
    //   title: "Course Catalog",
    //   description: "Create and manage the master course catalog records.",
    //   path: "/exam/course-catalog",
    //   icon: <BookMarked size={22} strokeWidth={2.5} />,
    //   color: "text-lime-600",
    //   bg: "bg-lime-100",
    //   accent: "bg-lime-600",
    // },
    // {
    //   title: "Student Registration",
    //   description: "Register students into their respective courses.",
    //   path: "/exam/student/registration",
    //   icon: <FilePlus2 size={22} strokeWidth={2.5} />,
    //   color: "text-emerald-600",
    //   bg: "bg-emerald-100",
    //   accent: "bg-emerald-600",
    // },
    {
      title: "Degree Audit",
      description:
        "Run the automated eligibility check (CGPA, credits, curriculum) that marks final-section students academically complete.",
      path: "/exam/degree-audit",
      icon: <ClipboardCheck size={22} strokeWidth={2.5} />,
      color: "text-teal-600",
      bg: "bg-teal-100",
      accent: "bg-teal-600",
    },
    {
      title: "Graduation Clearance",
      description:
        "Compile final grades and CGPA, check discipline cases and approve degree transcripts.",
      path: "/exam/graduation-clearance",
      icon: <Award size={22} strokeWidth={2.5} />,
      color: "text-emerald-600",
      bg: "bg-emerald-100",
      accent: "bg-emerald-600",
    },
    {
      title: "Academic History",
      description:
        "View a student's complete enrolled course history across all semesters.",
      path: "/exam/student/history",
      icon: <History size={22} strokeWidth={2.5} />,
      color: "text-violet-600",
      bg: "bg-violet-100",
      accent: "bg-violet-600",
    },
    {
      title: "Student Promotion",
      description:
        "Promote or demote students between sections, with fee-defaulter checks and accountant overrides.",
      path: "/exam/student/promotion",
      icon: <TrendingUp size={22} strokeWidth={2.5} />,
      color: "text-cyan-600",
      bg: "bg-cyan-100",
      accent: "bg-cyan-600",
    },
    {
      title: "Create Exam",
      description: "Schedule new exams, set subjects, and define criteria.",
      path: "/exam/create",
      icon: <FilePlus2 size={22} strokeWidth={2.5} />,
      color: "text-emerald-600",
      bg: "bg-emerald-100",
      accent: "bg-emerald-600",
    },
    {
      title: "Date Sheet",
      description: "Manage and publish the master examination schedule.",
      path: "/exam/schedule",
      icon: <CalendarDays size={22} strokeWidth={2.5} />,
      color: "text-orange-600",
      bg: "bg-orange-100",
      accent: "bg-orange-600",
    },
    {
      title: "Class Timetable",
      description: "Browse the weekly class schedule, filtered by class, program, or session.",
      path: "/exam/timetable",
      icon: <CalendarClock size={22} strokeWidth={2.5} />,
      color: "text-sky-600",
      bg: "bg-sky-100",
      accent: "bg-sky-600",
    },
    {
      title: "Admit Cards",
      description:
        "Generate and revoke student hall tickets / roll number slips.",
      path: "/exam/admit-cards",
      icon: <Ticket size={22} strokeWidth={2.5} />,
      color: "text-rose-600",
      bg: "bg-rose-100",
      accent: "bg-rose-600",
    },
    {
      title: "Marks Upload",
      description: "Enter and verify student marks per exam, one course at a time.",
      path: "/exam/marks-upload",
      icon: <UploadCloud size={22} strokeWidth={2.5} />,
      color: "text-indigo-600",
      bg: "bg-indigo-100",
      accent: "bg-indigo-600",
    },
    {
      title: "Exam Attendance",
      description: "Record exam attendance per section and submit it to the HOD for review.",
      path: "/exam/attendance",
      icon: <UserCheck size={22} strokeWidth={2.5} />,
      color: "text-teal-600",
      bg: "bg-teal-100",
      accent: "bg-teal-600",
    },
    {
      title: "Results & Grading",
      description: "View computed grades, GPA, and course-wise results per student.",
      path: "/exam/results",
      icon: <GraduationCap size={22} strokeWidth={2.5} />,
      color: "text-purple-600",
      bg: "bg-purple-100",
      accent: "bg-purple-600",
    },
    {
      title: "Re-evaluation Requests",
      description: "Manage student appeals for recounting or re-checking.",
      path: "/exam/appeals",
      icon: <FileSignature size={22} strokeWidth={2.5} />,
      color: "text-pink-600",
      bg: "bg-pink-100",
      accent: "bg-pink-600",
    },
    {
      title: "Disciplinary / UFM",
      description:
        "Log and resolve Unfair Means (cheating) committee decisions.",
      path: "/exam/ufm",
      icon: <AlertTriangle size={22} strokeWidth={2.5} />,
      color: "text-red-600",
      bg: "bg-red-100",
      accent: "bg-red-600",
    },
    {
      title: "Transcripts & Degrees",
      description:
        "Generate official transcripts, provisional certificates, and degrees.",
      path: "/exam/certification",
      icon: <Award size={22} strokeWidth={2.5} />,
      color: "text-yellow-600",
      bg: "bg-yellow-100",
      accent: "bg-yellow-600",
    },
  ];
};
