import {
  Users,
  Building2,
  CalendarDays,
  BookOpen,
  Layers,
  MonitorPlay,
  Activity,
  Users2,
  Trash2,
  GraduationCap,
  School,
} from "lucide-react";

export const getAdminLinks = () => {
  return [
    {
      id: 12,
      title: "Schools & Campuses",
      subtitle: "Multi-campus setup",
      path: "/admin/schools",
      description: "Create CISD schools, upload campus logos, and control which campuses are active.",
      icon: School,
      accent: "#65a30d",
      bg: "#f7fee7",
      category: "System",
    },
    {
      id: 1,
      title: "User Management",
      subtitle: "Directory & Roles",
      path: "/admin/users",
      description:
        "Create, view, update, and manage all registered users and permissions.",
      icon: Users,
      accent: "#2563eb",
      bg: "#eff6ff",
      category: "Users",
    },
    {
      id: 2,
      title: "Academic Structure",
      subtitle: "Departments & Programs",
      path: "/admin/academics",
      description: "Configure departments, faculties, and program structures.",
      icon: Building2,
      accent: "#7c3aed",
      bg: "#f5f3ff",
      category: "Academics",
    },
    {
      id: 3,
      title: "Session Management",
      subtitle: "Terms & Semesters",
      path: "/admin/sessions",
      description:
        "Create and manage academic sessions, terms, and timeline windows.",
      icon: CalendarDays,
      accent: "#db2777",
      bg: "#fdf2f8",
      category: "Academics",
    },
    {
      id: 4,
      title: "Course Catalog",
      subtitle: "Curriculum Control",
      path: "/admin/courses",
      description:
        "Add, update, and organize courses, syllabi, and credit-hour allocations.",
      icon: BookOpen,
      accent: "#d97706",
      bg: "#fffbeb",
      category: "Courses",
    },
    {
      id: 6,
      title: "LMS Control Panel",
      subtitle: "Digital Learning Access",
      path: "/admin/lms",
      description:
        "Configure LMS credentials, and block/unblock student portals.",
      icon: MonitorPlay,
      accent: "#dc2626",
      bg: "#fef2f2",
      category: "System",
    },
    {
      id: 7,
      title: "Activity Log",
      subtitle: "System-wide Audit Trail",
      path: "/admin/activity-logs",
      description:
        "See every create, update, and delete performed by every user, filter and review it, and export it.",
      icon: Activity,
      accent: "#4f46e5",
      bg: "#eef2ff",
      category: "System",
    },
    {
      id: 8,
      title: "Currently Logged In",
      subtitle: "Active Sessions",
      path: "/admin/active-sessions",
      description:
        "See every user logged in right now, from which device/IP, and force-logout any session.",
      icon: Users2,
      accent: "#059669",
      bg: "#ecfdf5",
      category: "System",
    },
    {
      id: 9,
      title: "Student Trash",
      subtitle: "Deleted Students",
      path: "/admin/student-trash",
      description:
        "Review every deleted student (University and College), restore them, or permanently delete before the 60-day retention window ends.",
      icon: Trash2,
      accent: "#e11d48",
      bg: "#fff1f2",
      category: "System",
    },
    {
      id: 10,
      title: "Clearance Offices",
      subtitle: "Graduation Sign-off Desks",
      path: "/admin/clearance-offices",
      description:
        "Manage the offices a graduating student must clear (Library, Transport, Hostel, IT & Labs, and others) and assign their officers.",
      icon: Building2,
      accent: "#0f766e",
      bg: "#f0fdfa",
      category: "Academics",
    },
    {
      id: 11,
      title: "Graduation Clearance",
      subtitle: "Degree Clearance Pipeline",
      path: "/registrar/graduation/clearances",
      description:
        "Follow every student through HOD, Exam Office, auxiliary offices, Accounts and Registrar; view the graduate list.",
      icon: GraduationCap,
      accent: "#4f46e5",
      bg: "#eef2ff",
      category: "Academics",
    },
  ];
};
