import React from "react";
import {
  UserCheck,
  CheckCircle,
  AlertTriangle,
  FileSignature,
  Users,
  BarChart4,
  CalendarDays,
  BookOpen,
  ClipboardList,
  UserMinus,
  CalendarCheck,
  Star,
  CalendarClock,
  GraduationCap,
} from "lucide-react";

export const HODLink = () => {
  return [
    {
      title: "Approve Attendance",
      description: "Review and finalize exam attendance rosters and shortages.",
      path: "/hod/approve-attendance",
      icon: <UserCheck size={22} strokeWidth={2.5} />,
      color: "text-teal-600",
      bg: "bg-teal-100",
      accent: "bg-teal-600",
    },
    {
      title: "Approve Marks",
      description: "Verify and sign off on uploaded midterm and final marks.",
      path: "/hod/approve-marks",
      icon: <CheckCircle size={22} strokeWidth={2.5} />,
      color: "text-indigo-600",
      bg: "bg-indigo-100",
      accent: "bg-indigo-600",
    },
    {
      title: "Approve UFM Cases",
      description:
        "Review Unfair Means reports and finalize committee actions.",
      path: "/hod/approve-ufm",
      icon: <AlertTriangle size={22} strokeWidth={2.5} />,
      color: "text-red-600",
      bg: "bg-red-100",
      accent: "bg-red-600",
    },
    {
      title: "Approve Rechecking",
      description: "Authorize student appeals and re-evaluation requests.",
      path: "/hod/approve-appeals",
      icon: <FileSignature size={22} strokeWidth={2.5} />,
      color: "text-pink-600",
      bg: "bg-pink-100",
      accent: "bg-pink-600",
    },
    {
      title: "Monitor Faculty & Courses",
      description:
        "Track exam publishing and marks-submission progress by faculty.",
      path: "/hod/monitor-courses",
      icon: <Users size={22} strokeWidth={2.5} />,
      color: "text-amber-600",
      bg: "bg-amber-100",
      accent: "bg-amber-600",
    },
    {
      title: "Department Reports",
      description:
        "View analytics on student performance, passing ratios, and KPIs.",
      path: "/hod/reports",
      icon: <BarChart4 size={22} strokeWidth={2.5} />,
      color: "text-purple-600",
      bg: "bg-purple-100",
      accent: "bg-purple-600",
    },
    {
      title: "Exam Coordination",
      description: "View your department's published exam schedule.",
      path: "/hod/exam-coordination",
      icon: <CalendarDays size={22} strokeWidth={2.5} />,
      color: "text-orange-600",
      bg: "bg-orange-100",
      accent: "bg-orange-600",
    },
    {
      title: "Department Students",
      description:
        "Browse your department's students by program and semester, with full profiles.",
      path: "/hod/students",
      icon: <GraduationCap size={22} strokeWidth={2.5} />,
      color: "text-indigo-600",
      bg: "bg-indigo-100",
      accent: "bg-indigo-600",
    },
    {
      title: "Graduation Clearance",
      description:
        "Verify final-year students' academics and start their degree clearance.",
      path: "/hod/graduation",
      icon: <GraduationCap size={22} strokeWidth={2.5} />,
      color: "text-emerald-600",
      bg: "bg-emerald-100",
      accent: "bg-emerald-600",
    },
    {
      title: "Department Courses",
      description: "Browse your department's course catalog.",
      path: "/hod/course/management",
      icon: <BookOpen size={22} strokeWidth={2.5} />,
      color: "text-violet-600",
      bg: "bg-violet-100",
      accent: "bg-violet-600",
    },
    {
      title: "Department Timetable",
      description: "Create and manage your department's weekly class timetable.",
      path: "/hod/timetable",
      icon: <CalendarClock size={22} strokeWidth={2.5} />,
      color: "text-orange-600",
      bg: "bg-orange-100",
      accent: "bg-orange-600",
    },
    {
      title: "Course Allocation",
      description: "Allocate courses to sessions, semesters, and instructors.",
      path: "/hod/course/allocation",
      icon: <ClipboardList size={22} strokeWidth={2.5} />,
      color: "text-cyan-600",
      bg: "bg-cyan-100",
      accent: "bg-cyan-600",
    },
    {
      title: "Course Withdrawals",
      description: "Withdraw a student from a course in your department.",
      path: "/hod/course/withdrawals",
      icon: <UserMinus size={22} strokeWidth={2.5} />,
      color: "text-rose-600",
      bg: "bg-rose-100",
      accent: "bg-rose-600",
    },
    {
      title: "Leave Requests",
      description: "Review and approve staff leave requests in your department.",
      path: "/hod/leaves",
      icon: <CalendarCheck size={22} strokeWidth={2.5} />,
      color: "text-blue-600",
      bg: "bg-blue-100",
      accent: "bg-blue-600",
    },
    {
      title: "Appraisals to Review",
      description: "Score KPIs and give feedback for staff who report to you.",
      path: "/hod/appraisals",
      icon: <Star size={22} strokeWidth={2.5} />,
      color: "text-amber-600",
      bg: "bg-amber-100",
      accent: "bg-amber-600",
    },
  ];
};
